server:
  port: 8888
  servlet:
    context-path: /validadordedocumento

spring:
  jpa:
    hibernate.ddl-auto: validate
    open-in-view: false
    properties.hibernate.dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    url: jdbc:mysql://localhost:3306/bancodigital?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
